# Task 1: Data Cleaning & Preprocessing — Titanic Dataset


## Objective

The objective of this project is to clean and preprocess the raw Titanic dataset so that it is suitable for further data analysis.

The following preprocessing tasks will be performed:

* Handle missing values
* Remove duplicate records
* Convert data types
* Rename columns
* Validate the cleaned dataset
* Export the final cleaned dataset

In [1]:
import pandas as pd

## 1. Load the Dataset

The Titanic dataset downloaded from Kaggle is loaded into a Pandas DataFrame for inspection and preprocessing.

In [2]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

## 2. Initial Dataset Inspection

Before performing any cleaning operations, the dataset is inspected to understand its structure, dimensions, column names, data types, and sample records.

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
df.shape

(891, 12)

In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [8]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [16]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

## 3. Handling Missing Values

Missing values can affect data analysis and may cause problems in later processing. Therefore, missing values are identified and analyzed before deciding how each affected column should be handled.

In [17]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### Missing Value Percentage

The percentage of missing values in each column is calculated to understand the extent of missing data.

In [18]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

Cabin          77.104377
Age            19.865320
Embarked        0.224467
PassengerId     0.000000
Name            0.000000
Pclass          0.000000
Survived        0.000000
Sex             0.000000
Parch           0.000000
SibSp           0.000000
Fare            0.000000
Ticket          0.000000
dtype: float64

In [19]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [20]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

### Missing Value Treatment

The following approach is used to handle missing values:

* `Age`: Missing values are replaced using the median.
* `Embarked`: Missing values are replaced using the mode.
* `Cabin`: The column is removed because it contains a large proportion of missing values.

In [21]:
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

df.drop(columns=["Cabin"], inplace=True)

### Verification

After handling the missing values, the dataset is checked again to confirm that no missing values remain in the retained columns.

In [22]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## 4. Removing Duplicate Records

Duplicate records can cause the same observation to be counted more than once. Therefore, duplicate rows are identified and removed from the dataset.

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df = df.drop_duplicates()

In [25]:
df.duplicated().sum()

np.int64(0)

## 5. Data Type Conversion

The data types of the columns are reviewed and converted where appropriate to ensure that numerical and categorical variables use suitable data types.

In [26]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Embarked           str
dtype: object

In [27]:
df["PassengerId"] = df["PassengerId"].astype("int64")
df["Survived"] = df["Survived"].astype("int64")
df["Pclass"] = df["Pclass"].astype("int64")
df["SibSp"] = df["SibSp"].astype("int64")
df["Parch"] = df["Parch"].astype("int64")

df["Age"] = df["Age"].astype("float64")
df["Fare"] = df["Fare"].astype("float64")

In [29]:
df["Sex"] = df["Sex"].astype("category")
df["Embarked"] = df["Embarked"].astype("category")

In [30]:
df.dtypes

PassengerId       int64
Survived          int64
Pclass            int64
Name                str
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket              str
Fare            float64
Embarked       category
dtype: object

## 6. Renaming Columns

The column names are standardized using lowercase letters and underscores to improve readability and maintain a consistent naming convention.

In [31]:
df.rename(columns={
    "PassengerId": "passenger_id",
    "Survived": "survived",
    "Pclass": "passenger_class",
    "Name": "name",
    "Sex": "sex",
    "Age": "age",
    "SibSp": "siblings_spouses",
    "Parch": "parents_children",
    "Ticket": "ticket",
    "Fare": "fare",
    "Embarked": "embarked"
}, inplace=True)

In [32]:
df.columns

Index(['passenger_id', 'survived', 'passenger_class', 'name', 'sex', 'age',
       'siblings_spouses', 'parents_children', 'ticket', 'fare', 'embarked'],
      dtype='str')

## 7. Final Dataset Validation

The cleaned dataset is inspected one final time to verify that missing values, duplicate records, data types, column names, and dataset dimensions have been handled correctly.

In [34]:
df.head()

,passenger_id,survived,passenger_class,name,sex,age,siblings_spouses,parents_children,ticket,fare,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [33]:
df.shape

(891, 11)

In [35]:
df.isnull().sum()

passenger_id        0
survived            0
passenger_class     0
name                0
sex                 0
age                 0
siblings_spouses    0
parents_children    0
ticket              0
fare                0
embarked            0
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
df.dtypes

passenger_id           int64
survived               int64
passenger_class        int64
name                     str
sex                 category
age                  float64
siblings_spouses       int64
parents_children       int64
ticket                   str
fare                 float64
embarked            category
dtype: object

In [38]:
df.columns

Index(['passenger_id', 'survived', 'passenger_class', 'name', 'sex', 'age',
       'siblings_spouses', 'parents_children', 'ticket', 'fare', 'embarked'],
      dtype='str')

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   passenger_id      891 non-null    int64
 1   survived          891 non-null    int64
 2   passenger_class   891 non-null    int64
 3   name              891 non-null    str
 4   sex               891 non-null    category
 5   age               891 non-null    float64
 6   siblings_spouses  891 non-null    int64
 7   parents_children  891 non-null    int64
 8   ticket            891 non-null    str
 9   fare              891 non-null    float64
 10  embarked          891 non-null    category
dtypes: category(2), float64(2), int64(5), str(2)
memory usage: 64.6 KB

## 8. Export the Cleaned Dataset

The final cleaned dataset is exported as a separate CSV file so that it can be used for further analysis without modifying the original raw dataset.

In [44]:
df.to_csv("../data/Titanic-Dataset_Cleaned.csv", index=False)

In [45]:
cleaned_df = pd.read_csv("../data/Titanic-Dataset_Cleaned.csv")

cleaned_df.head()

,passenger_id,survived,passenger_class,name,sex,age,siblings_spouses,parents_children,ticket,fare,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [42]:
cleaned_df.shape

(891, 11)

## 9. Conclusion

The Titanic dataset was successfully cleaned and preprocessed for further analysis.

The following preprocessing operations were completed:

* Missing values in `Age` were handled using the median.
* Missing values in `Embarked` were handled using the mode.
* The `Cabin` column was removed because it contained a large proportion of missing values.
* Duplicate records were checked and removed.
* Appropriate data types were assigned to numerical and categorical columns.
* Column names were standardized using lowercase letters and underscores.
* The cleaned dataset was validated.
* The final dataset was exported as `Titanic-Cleaned.csv`.

The resulting dataset is now clean and ready for further data analysis.